# Generated by Django 2.2 on 2019-06-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geo.Provider'),
            preserve_default=False,
        ),
    ]
