# Generated by Django 2.2 on 2019-06-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_servicearea_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='geo.Provider'),
        ),
    ]
